version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8021:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www/laravel
      - ./frontend/dist:/var/www/vue
      - ./certs/domain.crt:/etc/ssl/certs/domain.crt
      - ./certs/domain.key:/etc/ssl/private/domain.key
      # Опционально, если есть CA-сертификат:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
    depends_on:
      - php
      - frontend

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ./backend:/var/www/laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "8101:3306"
      - "8443:443"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  frontend:
    image: node:20
    container_name: frontend
    volumes:
      - ./frontend:/var/www/vue
